### ISSUE TITLE
Getting console error on encrypt

### ISSUE THREAD

**Issue by ghost** [mediaupstream/SublimeText-Crypto#13]
I open a new tab, write some text, select it and try to encrypt,
plugin asks for password, i'm typing it (i typed "root" if that matters) and it displays the following in the console.

Error: [WinError 2] The system cannot find the file specified

I tried to save the tab, didnt work, also tried this on two machines both appear to have same problem.
I use sublime text 3, win7 virtual machine...

**Comment by arnokret** [comment]
On a windows 8.1 machine I get the error

Error: [WinError 5] Access is denied

when trying to encrypt. 

I expect that it's the following problem: A Window program (as opposed to Linux/Mac) locks a file when opened. Since Sublime Text has the file already open, it is not possible for openssl to change it?
