### ISSUE TITLE
[Question] How Crypto protect my private data?

### ISSUE THREAD

**Issue by Kristinita** [mediaupstream/SublimeText-Crypto#17]
### 1. Briefly

It would be nice, if you write in `README.MD`, how Crypto to work.

### 2. Detail

Users can afraid for security of their private information. For example, I encrypt my text use Crypto and my enemy got encrypted file but he don't know my password.

• Where is stored my Crypto password?
• May my enemy discover my password, if he has all files of my Sublime Text?

Thanks.

**Comment by mediaupstream** [comment]
Hi @Kristinita 
This plugin uses [OpenSSL](https://www.openssl.org/) to encrypt and decrypt the text content of a file. For example you can run this command in your terminal to encrypt some text:

```bash
echo "Hello World" | openssl enc -des3 -base64
```
This command encrypts the text *"Hello World"* using the `Triple DES` symmetric cipher and converts that binary into Base64 so it can be output as a string.

When you run this command in the terminal `openssl` asks you to type in a password, the password is not stored anywhere in your system. I don't think a user can extract the password from the cipher output, however if your password is not very strong they could probably find the password using a dictionary attack / rainbow table attack, etc. So, use strong passwords!

Using the `openssl` command is probably safer than using this SublimeText plugin!

Why? Because, currently the password is entered as visible plain text, whereas in the terminal the password is never shown while being entered.

There is a PR to address this, but I haven't had time to inspect it...

**Comment by mediaupstream** [comment]
You could use an alias (if you are using linux / osx) in your .bash_profile
```bash
alias encrypt='openssl enc -des3'
alias decrypt='openssl enc -d -des3'
```
then you can encrypt and decrypt files like this:
```bash
# encrypt the file
cat myPasswords.txt | encrypt > myPasswords_encrypted.o

# decrypt the encrypted file
cat myPasswords_encrypted.o | decrypt > myPasswords.txt
```

**Comment by mediaupstream** [comment]
you would want to also securely remove the "myPasswords.txt" file after encrypting, using something like `scr myPasswords.txt`...

Is all of this secure? relatively. Any attacker who is sufficiently motivated can probably gain access to your files...

**Comment by Kristinita** [comment]
@mediaupstream , thanks for a detailed answer!

> There is a PR to address this, but I haven't had time to inspect it...

I need, you review it.

Also, it would be nice, if you add [**enscryption_on_save**](https://github.com/mediaupstream/SublimeText-Crypto#todo) option for more privacy.

Thanks.
